name: CI

# TODO: Don't do this! Use GitHub's encrypted secrets and set the value of the
# variable as ${{ secrets.RAILS_MASTER_KEY }}
# Ref: https://docs.github.com/en/actions/reference/encrypted-secrets
env:
  RAILS_MASTER_KEY: 02a9ea770b4985659e8ce92699f218dc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Ruby specs
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      ES_HOST: 127.0.0.1
      ELASTICSEARCH_URL: http://127.0.0.1:9200

    services:
      mysql:
        image: mysql:5.7.36
        ports: ['3306:3306']
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
      redis:
        image: redis:5.0
        ports: ['6379:6379']
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        env:
          cluster.name: es-cluster
          discovery.type: single-node
          xpack.security.enabled: false
          transport.host: localhost
          network.host: 127.0.0.1
          http.host: 0.0.0.0
          http.cors.enabled: true
          http.cors.allow-origin: '*'
          ES_JAVA_OPTS: '-Xms512m -Xmx512m'
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
        - 9200:9200
    steps:
    - uses: actions/checkout@v3
    - uses: nanasess/setup-chromedriver@v1
    - name: Install System Dependencies
      run: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install g++ qtbase5-dev qt5-qmake libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x nano libcurl4 libcurl4-openssl-dev libmagickcore-dev libmagickwand-dev imagemagick xvfb nodejs
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6'
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Yarn
      run:  yarn
    - name: Set up Database
      run: bundle exec rails db:prepare
    - name: Run specs
      run: bundle exec rake spec
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: 'coverage/lcov.info'
