name: Security Audits

on:
  schedule:
    - cron: '30 8 * * 5'

permissions:
  contents: read

jobs:
  bundle_audit:
    name: Bundle audit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install System Dependencies
      run: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install g++ qtbase5-dev qt5-qmake libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x nano libcurl4 libcurl4-openssl-dev libmagickcore-dev libmagickwand-dev imagemagick xvfb nodejs
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6'
        bundler-cache: false
    - name: Bundle audit
      run: |
        gem install bundler-audit
        bundle audit check --update

  bundle_leak:
    name: Bundle leak
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install System Dependencies
      run: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install g++ qtbase5-dev qt5-qmake libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x nano libcurl4 libcurl4-openssl-dev libmagickcore-dev libmagickwand-dev imagemagick xvfb nodejs
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6'
        bundler-cache: false
    - name: Bundle leak
      run: |
        gem install bundler-leak
        bundle leak check --update

  yarn_audit:
    name: Yarn audit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install System Dependencies
      run: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install g++ qtbase5-dev qt5-qmake libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x nano libcurl4 libcurl4-openssl-dev libmagickcore-dev libmagickwand-dev imagemagick xvfb nodejs
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Yarn audit
      run: |
        yarn audit
